table Opleidingen
	lineageTag: c375e505-96bb-406f-899f-a3235fe9165a

	column Opleiding_ID
		dataType: string
		lineageTag: e8bde83c-e260-4f76-bc9e-673ca2351e37
		summarizeBy: none
		sourceColumn: Opleiding_ID

		annotation SummarizationSetBy = Automatic

	column Departement_ID
		dataType: string
		lineageTag: 760f4c5f-cc05-4ee3-9acd-db5fa9c44786
		summarizeBy: none
		sourceColumn: Departement_ID

		annotation SummarizationSetBy = Automatic

	column Naam
		dataType: string
		lineageTag: 1176efba-e6d4-4d99-8b54-f2dc0adb7cd4
		summarizeBy: none
		sourceColumn: Naam

		annotation SummarizationSetBy = Automatic

	column ECTS
		dataType: int64
		formatString: 0
		lineageTag: db87527b-16c6-4883-b913-24441c182d8d
		summarizeBy: sum
		sourceColumn: ECTS

		annotation SummarizationSetBy = Automatic

	column 'Departementen.Naam'
		dataType: string
		lineageTag: 9c0ab26f-e689-41d2-85da-4b52c6b14ab8
		summarizeBy: none
		sourceColumn: Departementen.Naam

		annotation SummarizationSetBy = Automatic

	hierarchy 'Departementen.Naam Hierarchy'
		lineageTag: 54c93478-a8dc-4277-9421-940a2c816d58

		level 'Departementen.Naam'
			lineageTag: 4bf8be10-fa5a-4599-b304-883cac5f23c8
			column: 'Departementen.Naam'

		level Naam
			lineageTag: 25915c84-7ae6-4df7-8824-4ae0f797e795
			column: Naam

	partition Opleidingen = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(FilePath), null, true),
				    Opleidingen_Sheet = Source{[Item="Opleidingen",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Opleidingen_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Opleiding_ID", type text}, {"Departement_ID", type text}, {"Naam", type text}, {"ECTS", Int64.Type}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Departement_ID"}, Departementen, {"Departement_ID"}, "Departementen", JoinKind.LeftOuter),
				    #"Expanded Departementen" = Table.ExpandTableColumn(#"Merged Queries", "Departementen", {"Naam"}, {"Departementen.Naam"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expanded Departementen",{"Opleiding_ID", "Naam", "ECTS", "Departement_ID", "Departementen.Naam"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

